version: '3.7'
services:


  

  pgadmin:
    image: dockage/phppgadmin:latest
    container_name: pgadmin_sellpump
    restart: always
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=174.138.31.4
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_SSL_MODE=disable
    ports:
      - 8081:80
    networks:
      sellpump:
        ipv4_address: 172.20.0.2
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  kategori :
    build: /root/sellpump_backend/kategori_microservice
    container_name: sellpump_service_kategori 
    image: sellpump_service_kategori 
    ports:
      - 2204:2204
    networks:
      sellpump:
        ipv4_address: 172.20.0.54
    volumes:
      - SellpumpFiles:/files
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/root/sellpump_backend/kategori_microservice:/logs"

volumes:
  PostgresSellpump:
    driver: local

  SellpumpFiles:
    driver: local

networks:
  sellpump:
    name : sellpump
    ipam:
      config:
        - subnet: 172.20.0.0/16